[package]
name = "GUI_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "*"
egui = "*"

[[bin]]
name = "GUI_1"
path = "src/main.rs"
